[package]
name = "dioxus-test"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { version = "0.7.5", features = [] }

[lints.clippy]
needless_return = "allow"

# enable more optimization in the release profile at the cost of compile time
[profile.release]
# do a second optimization pass over the entire program, including dependencies
lto = "thin"

# optimize for size in the wasm-release profile to reduce load times and bandwidth usage on web
[profile.wasm-release]
# default to release profile values
inherits = "release"

# optimize with size in mind (also try "z", sometimes it is better)
# slightly slows compile times, great improvements to file size and runtime performance
opt-level = "s"

# strip all debugging information from the binary to slightly reduce file size
strip = "debuginfo"

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
