# for using mold as the linker on linux:
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold", "-Zshare-generics=y"]

# for using lld as the linker on linux:
# [target.x86_64-unknown-linux-gnu]
# linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]

# mold isnt available on windows, so just use lld
[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"

# macos linker is cracked as hell for some reason and is faster than lld and just as fast as mold

# faster nightly codegen backend, doesn't work for wasm and sometimes macos
[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"

[profile.dev.package."*"]
codegen-backend = "llvm"
